class PostsController < ApplicationController
  Post = Struct.new(:permalink, :image_name, :content)

  def post
    @posts = []
    @posts << Post.new("MOVIES", "jedi-cats.gif", "Lorem ipsum dolor sit amet, eos et dicat congue propriae, ex soluta omnium mei. Postea principes ex has, aeque dolor mucius per et. Audiam inimicus omittantur est eu. Pri ei fabulas evertitur. Vis quod quas ei. Esse timeam sit ea, ne vel fugit falli. Mei decore labitur et, ad has accusata vulputate. Eos in quot vero eirmod. Eam no persius urbanitas mnesarchum, cum affert persius suscipiantur no. Ut iisque argumentum his, mea scaevola expetenda ne. Pro melius tamquam consulatu at, veniam volumus patrioque sit eu. Mei zril aliquam maiorum ei, eu vix phaedrum definitionem, pri cibo inani iisque te. Vidisse repudiandae ut mel, ex mei minimum interpretaris. Nam euripidis mnesarchum ex, aliquid bonorum tibique his in, an deleniti adipiscing argumentum vel. Te eos porro tamquam omittam, omnes graeci semper mel at.[1]")
    
    @posts << Post.new("ART & CULTURE", "ghetto-monalisa.gif", "Vidit illum equidem no eum. Nostrud constituam consequuntur ei ius. Eu mei phaedrum eleifend, id usu electram tractatos. Eu est diam vidisse nonumes, adolescens disputationi necessitatibus mea ne. Te aeque appellantur mel, an cibo fastidii percipit his. Est ei ipsum inani splendide, eam ullum animal voluptua an. Pri erat erant id, meliore senserit appellantur cu mea. Usu ut amet case voluptatum, pro clita honestatis ad. Eu mea esse partem erroribus, in eum alii melius, case omnium volutpat no his. Mel iudico eligendi detraxit an. Adhuc nemore incorrupte eam in.")

    @posts << Post.new("FITNESS", "fight-club.gif", "Ei nihil constituam vim, ne mundi affert appellantur est. Ludus argumentum cum ne, vel ut soluta diceret. Feugait sadipscing mei ne. Cu eam primis nostro, ei dicit eligendi per. Ea ius oratio vocent inermis, illum platonem nec et. Cu ius simul libris praesent, duo mucius quaestio ne. Cum falli pertinax hendrerit ad, liber decore vix cu. Ullum graeci patrioque sea no. Est quaestio gubergren deterruisset ad, vim ceteros ullamcorper ad. Dico posse aliquip no qui, his ludus constituto suscipiantur at. Praesent similique voluptaria has in, ea sea eligendi expetendis incorrupte. Eam regione detracto et. Sea illum commune philosophia ea. Eu brute docendi eum. Esse melius mea ea, id appellantur theophrastus has, id harum utamur commodo eos. Iudicabit accusamus quo ea. Usu ei eripuit volumus. Et hinc essent prodesset per, vix dicit populo interpretaris ea. Ne sed voluptua adipisci. Has agam unum pertinacia eu, case delicatissimi eum et. Persius molestiae no nec, esse labitur ut mel, sea ne stet integre copiosae. Nihil fabellas mei ex, et vis quando suscipiantur, et iusto vivendum duo. Ius ut novum nullam salutatus, et pri illud definitiones.")
    
    @posts << Post.new("SURFING", "dogsurf.gif", "Duo in invidunt sententiae. An equidem repudiandae nec, vix minim dolore tincidunt an. Te est cetero lucilius postulant. Iisque menandri evertitur vim eu. Has suscipit facilisis ut, id diam postulant pro, vis ornatus pericula ad. Mel labore scripserit quaerendum ei, etiam omittam usu ad, eu iusto verear officiis sea. Sit cu graeci dicunt everti, ius eu decore habemus comprehensam.")

    @post = @posts.find {|p| p.permalink == params[:id]}

  end

  def index
     @posts = []
     @posts << Post.new("MOVIES", "jedi-cats.gif", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sodales ligula in libero.")
     
     @posts << Post.new("ART & CULTURE", "ghetto-monalisa.gif", "Integer euismod lacus luctus magna. Quisque cursus, metus vitae pharetra auctor, sem massa mattis sem, at interdum magna augue eget diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi lacinia molestie dui. Praesent blandit dolor. Sed non quam. In vel mi sit amet augue congue elementum. Morbi in ipsum sit amet pede facilisis laoreet. Donec lacus nunc, viverra nec, blandit vel, egestas et, augue. Vestibulum tincidunt malesuada tellus. Ut ultrices ultrices enim. Curabitur sit amet mauris. Morbi in dui quis est pulvinar ullamcorper. Nulla facilisi. Integer lacinia sollicitudin massa. Cras metus. Sed aliquet risus a tortor. Integer id quam. Morbi mi. Quisque nisl felis, venenatis tristique, dignissim in, ultrices sit amet, augue. Proin sodales libero eget ante. Nulla quam. Aenean laoreet. Vestibulum nisi lectus, commodo ac, facilisis ac, ultricies eu, pede. Ut orci risus, accumsan porttitor, cursus quis, aliquet eget, justo.")
     
     @posts << Post.new("FITNESS", "fight-club.gif", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sodales ligula in libero. Sed dignissim lacinia nunc. Curabitur tortor. Pellentesque nibh. Aenean quam. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam nec ante. Sed lacinia, urna non tincidunt mattis, tortor neque adipiscing diam, a cursus ipsum ante quis turpis. Nulla facilisi. Ut fringilla. Suspendisse potenti. Nunc feugiat mi a tellus consequat imperdiet. Vestibulum sapien. Proin quam. Etiam ultrices. Suspendisse in justo eu magna luctus suscipit. Sed lectus. Integer euismod lacus luctus magna. Quisque cursus, metus vitae pharetra auctor, sem massa mattis sem, at interdum magna augue eget diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi lacinia molestie dui. Praesent blandit dolor. Sed non quam. In vel mi sit amet augue congue elementum. Morbi in ipsum sit amet pede facilisis laoreet. Donec lacus nunc, viverra nec, blandit vel, egestas et, augue. Vestibulum tincidunt malesuada tellus. Ut ultrices ultrices enim. Curabitur sit amet mauris. Morbi in dui quis est pulvinar ullamcorper. Nulla facilisi. Integer lacinia sollicitudin massa. Cras metus. Sed aliquet risus a tortor. Integer id quam. Morbi mi. Quisque nisl felis, venenatis tristique, dignissim in, ultrices sit amet, augue. Proin sodales libero eget ante. Nulla quam.")
     
     @posts << Post.new("SURFING", "dogsurf.gif", "Sed dignissim lacinia nunc. Curabitur tortor. Pellentesque nibh. Aenean quam. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam nec ante. Sed lacinia, urna non tincidunt mattis, tortor neque adipiscing diam, a cursus ipsum ante quis turpis. Nulla facilisi. Ut fringilla. Suspendisse potenti. Nunc feugiat mi a tellus consequat imperdiet. Vestibulum sapien. Proin quam. Etiam ultrices. Suspendisse in justo eu magna luctus suscipit. Sed lectus.")

    @post = @posts.last

 end

end
